from enum import Enum

class Gender(Enum):
    MALE = 'm'
    FEMALE = 'f'

class Country(Enum):
    
    AF = "Afghanistan"
    AX = "Åland Islands"
    AL = "Albania"
    DZ = "Algeria"
    AS = "American Samoa"
    AD = "Andorra"
    AO = "Angola"
    AI = "Anguilla"
    AQ = "Antarctica"
    AG = "Antigua and Barbuda"
    AR = "Argentina"
    AM = "Armenia"
    AW = "Aruba"
    AU = "Australia"
    AT = "Austria"
    AZ = "Azerbaijan"
    BS = "Bahamas"
    BH = "Bahrain"
    BD = "Bangladesh"
    BB = "Barbados"
    BY = "Belarus"
    BE = "Belgium"
    BZ = "Belize"
    BJ = "Benin"
    BM = "Bermuda"
    BT = "Bhutan"
    BO = "Bolivia"
    BQ = "Bonaire, Sint Eustatius and Saba"
    BA = "Bosnia and Herzegovina"
    BW = "Botswana"
    BV = "Bouvet Island"
    BR = "Brazil"
    IO = "British Indian Ocean Territory"
    BN = "Brunei Darussalam"
    BG = "Bulgaria"
    BF = "Burkina Faso"
    BI = "Burundi"
    CV = "Cabo Verde"
    KH = "Cambodia"
    CM = "Cameroon"
    CA = "Canada"
    KY = "Cayman Islands"
    CF = "Central African Republic"
    TD = "Chad"
    CL = "Chile"
    CN = "China"
    CX = "Christmas Island"
    CC = "Cocos (Keeling) Islands"
    CO = "Colombia"
    KM = "Comoros"
    CG = "Congo"
    CD = "Congo (Democratic Republic of the)"
    CK = "Cook Islands"
    CR = "Costa Rica"
    CI = "Côte d'Ivoire"
    HR = "Croatia"
    CU = "Cuba"
    CW = "Curaçao"
    CY = "Cyprus"
    CZ = "Czechia"
    DK = "Denmark"
    DJ = "Djibouti"
    DM = "Dominica"
    DO = "Dominican Republic"
    EC = "Ecuador"
    EG = "Egypt"
    SV = "El Salvador"
    GQ = "Equatorial Guinea"
    ER = "Eritrea"
    EE = "Estonia"
    SZ = "Eswatini"
    ET = "Ethiopia"
    FK = "Falkland Islands (Malvinas)"
    FO = "Faroe Islands"
    FJ = "Fiji"
    FI = "Finland"
    FR = "France"
    GF = "French Guiana"
    PF = "French Polynesia"
    TF = "French Southern Territories"
    GA = "Gabon"
    GM = "Gambia"
    GE = "Georgia"
    DE = "Germany"
    GH = "Ghana"
    GI = "Gibraltar"
    GR = "Greece"
    GL = "Greenland"
    GD = "Grenada"
    GP = "Guadeloupe"
    GU = "Guam"
    GT = "Guatemala"
    GG = "Guernsey"
    GN = "Guinea"
    GW = "Guinea-Bissau"
    GY = "Guyana"
    HT = "Haiti"
    HM = "Heard Island and McDonald Islands"
    VA = "Holy See"
    HN = "Honduras"
    HK = "Hong Kong"
    HU = "Hungary"
    IS = "Iceland"
    IN = "India"
    ID = "Indonesia"
    IR = "Iran"
    IQ = "Iraq"
    IE = "Ireland"
    IM = "Isle of Man"
    IL = "Israel"
    IT = "Italy"
    JM = "Jamaica"
    JP = "Japan"
    JE = "Jersey"
    JO = "Jordan"
    KZ = "Kazakhstan"
    KE = "Kenya"
    KI = "Kiribati"
    KP = "Korea (Democratic People's Republic of)"
    KR = "Korea (Republic of)"
    KW = "Kuwait"
    KG = "Kyrgyzstan"
    LA = "Lao People's Democratic Republic"
    LV = "Latvia"
    LB = "Lebanon"
    LS = "Lesotho"
    LR = "Liberia"
    LY = "Libya"
    LI = "Liechtenstein"
    LT = "Lithuania"
    LU = "Luxembourg"
    MO = "Macao"
    MG = "Madagascar"
    MW = "Malawi"
    MY = "Malaysia"
    MV = "Maldives"
    ML = "Mali"
    MT = "Malta"
    MH = "Marshall Islands"
    MQ = "Martinique"
    MR = "Mauritania"
    MU = "Mauritius"
    YT = "Mayotte"
    MX = "Mexico"
    FM = "Micronesia (Federated States of)"
    MD = "Moldova (Republic of)"
    MC = "Monaco"
    MN = "Mongolia"
    ME = "Montenegro"
    MS = "Montserrat"
    MA = "Morocco"
    MZ = "Mozambique"
    MM = "Myanmar"
    NA = "Namibia"
    NR = "Nauru"
    NP = "Nepal"
    NL = "Netherlands"
    NC = "New Caledonia"
    NZ = "New Zealand"
    NI = "Nicaragua"
    NE = "Niger"
    NG = "Nigeria"
    NU = "Niue"
    NF = "Norfolk Island"
    MK = "North Macedonia"
    MP = "Northern Mariana Islands"
    NO = "Norway"
    OM = "Oman"
    PK = "Pakistan"
    PW = "Palau"
    PS = "Palestine, State of"
    PA = "Panama"
    PG = "Papua New Guinea"
    PY = "Paraguay"
    PE = "Peru"
    PH = "Philippines"
    PN = "Pitcairn"
    PL = "Poland"
    PT = "Portugal"
    PR = "Puerto Rico"
    QA = "Qatar"
    RE = "Réunion"
    RO = "Romania"
    RU = "Russian Federation"
    RW = "Rwanda"
    BL = "Saint Barthélemy"
    SH = "Saint Helena, Ascension and Tristan da Cunha"
    KN = "Saint Kitts and Nevis"
    LC = "Saint Lucia"
    MF = "Saint Martin (French part)"
    PM = "Saint Pierre and Miquelon"
    VC = "Saint Vincent and the Grenadines"
    WS = "Samoa"
    SM = "San Marino"
    ST = "Sao Tome and Principe"
    SA = "Saudi Arabia"
    SN = "Senegal"
    RS = "Serbia"
    SC = "Seychelles"
    SL = "Sierra Leone"
    SG = "Singapore"
    SX = "Sint Maarten (Dutch part)"
    SK = "Slovakia"
    SI = "Slovenia"
    SB = "Solomon Islands"
    SO = "Somalia"
    ZA = "South Africa"
    GS = "South Georgia and the South Sandwich Islands"
    SS = "South Sudan"
    ES = "Spain"
    LK = "Sri Lanka"
    SD = "Sudan"
    SR = "Suriname"
    SJ = "Svalbard and Jan Mayen"
    SE = "Sweden"
    CH = "Switzerland"
    SY = "Syrian Arab Republic"
    TW = "Taiwan"
    TJ = "Tajikistan"
    TZ = "Tanzania, United Republic of"
    TH = "Thailand"
    TL = "Timor-Leste"
    TG = "Togo"
    TK = "Tokelau"
    TO = "Tonga"
    TT = "Trinidad and Tobago"
    TN = "Tunisia"
    TR = "Turkey"
    TM = "Turkmenistan"
    TC = "Turks and Caicos Islands"
    TV = "Tuvalu"
    UG = "Uganda"
    UA = "Ukraine"
    AE = "United Arab Emirates"
    GB = "United Kingdom of Great Britain and Northern Ireland"
    US = "United States of America"
    UM = "United States Minor Outlying Islands"
    UY = "Uruguay"
    UZ = "Uzbekistan"
    VU = "Vanuatu"
    VE = "Venezuela (Bolivarian Republic of)"
    VN = "Viet Nam"
    VG = "Virgin Islands (British)"
    VI = "Virgin Islands (U.S.)"
    WF = "Wallis and Futuna"
    EH = "Western Sahara"
    YE = "Yemen"
    ZM = "Zambia"
    ZW = "Zimbabwe"


class Currency(Enum):
    AED = "United Arab Emirates Dirham"
    AFN = "Afghan Afghani"
    ALL = "Albanian Lek"
    AMD = "Armenian Dram"
    ANG = "Netherlands Antillean Guilder"
    AOA = "Angolan Kwanza"
    ARS = "Argentine Peso"
    AUD = "Australian Dollar"
    AWG = "Aruban Florin"
    AZN = "Azerbaijani Manat"
    BAM = "Bosnia-Herzegovina Convertible Mark"
    BBD = "Barbadian Dollar"
    BDT = "Bangladeshi Taka"
    BGN = "Bulgarian Lev"
    BHD = "Bahraini Dinar"
    BMD = "Bermudian Dollar"
    BND = "Brunei Dollar"
    BOB = "Bolivian Boliviano"
    BRL = "Brazilian Real"
    BSD = "Bahamian Dollar"
    BTN = "Bhutanese Ngultrum"
    BWP = "Botswana Pula"
    BYN = "Belarusian Ruble"
    BZD = "Belize Dollar"
    CAD = "Canadian Dollar"
    CDF = "Congolese Franc"
    CHF = "Swiss Franc"
    CLP = "Chilean Peso"
    CNY = "Chinese Yuan"
    COP = "Colombian Peso"
    CRC = "Costa Rican Colón"
    CUP = "Cuban Peso"
    CVE = "Cape Verdean Escudo"
    CZK = "Czech Koruna"
    DJF = "Djiboutian Franc"
    DKK = "Danish Krone"
    DOP = "Dominican Peso"
    DZD = "Algerian Dinar"
    EGP = "Egyptian Pound"
    ERN = "Eritrean Nakfa"
    ETB = "Ethiopian Birr"
    EUR = "Euro"
    FJD = "Fijian Dollar"
    FKP = "Falkland Islands Pound"
    GBP = "British Pound Sterling"
    GEL = "Georgian Lari"
    GHS = "Ghanaian Cedi"
    GIP = "Gibraltar Pound"
    GMD = "Gambian Dalasi"
    GNF = "Guinean Franc"
    GTQ = "Guatemalan Quetzal"
    GYD = "Guyanese Dollar"
    HKD = "Hong Kong Dollar"
    HNL = "Honduran Lempira"
    HRK = "Croatian Kuna"
    HTG = "Haitian Gourde"
    HUF = "Hungarian Forint"
    IDR = "Indonesian Rupiah"
    ILS = "Israeli New Shekel"
    INR = "Indian Rupee"
    IQD = "Iraqi Dinar"
    IRR = "Iranian Rial"
    ISK = "Icelandic Króna"
    JMD = "Jamaican Dollar"
    JOD = "Jordanian Dinar"
    JPY = "Japanese Yen"
    KES = "Kenyan Shilling"
    KGS = "Kyrgyzstani Som"
    KHR = "Cambodian Riel"
    KMF = "Comorian Franc"
    KRW = "South Korean Won"
    KWD = "Kuwaiti Dinar"
    KYD = "Cayman Islands Dollar"
    KZT = "Kazakhstani Tenge"
    LAK = "Lao Kip"
    LBP = "Lebanese Pound"
    LKR = "Sri Lankan Rupee"
    LRD = "Liberian Dollar"
    LSL = "Lesotho Loti"
    LYD = "Libyan Dinar"
    MAD = "Moroccan Dirham"
    MDL = "Moldovan Leu"
    MGA = "Malagasy Ariary"
    MKD = "Macedonian Denar"
    MMK = "Myanmar Kyat"
    MNT = "Mongolian Tögrög"
    MOP = "Macanese Pataca"
    MRU = "Mauritanian Ouguiya"
    MUR = "Mauritian Rupee"
    MVR = "Maldivian Rufiyaa"
    MWK = "Malawian Kwacha"
    MXN = "Mexican Peso"
    MYR = "Malaysian Ringgit"
    MZN = "Mozambican Metical"
    NAD = "Namibian Dollar"
    NGN = "Nigerian Naira"
    NIO = "Nicaraguan Córdoba"
    NOK = "Norwegian Krone"
    NPR = "Nepalese Rupee"
    NZD = "New Zealand Dollar"
    OMR = "Omani Rial"
    PAB = "Panamanian Balboa"
    PEN = "Peruvian Sol"
    PGK = "Papua New Guinean Kina"
    PHP = "Philippine Peso"
    PKR = "Pakistani Rupee"
    PLN = "Polish Złoty"
    PYG = "Paraguayan Guaraní"
    QAR = "Qatari Riyal"
    RON = "Romanian Leu"
    RSD = "Serbian Dinar"
    RUB = "Russian Ruble"
    RWF = "Rwandan Franc"
    SAR = "Saudi Riyal"
    SBD = "Solomon Islands Dollar"
    SCR = "Seychellois Rupee"
    SDG = "Sudanese Pound"
    SEK = "Swedish Krona"
    SGD = "Singapore Dollar"
    SHP = "Saint Helena Pound"
    SLL = "Sierra Leonean Leone"
    SOS = "Somali Shilling"
    SRD = "Surinamese Dollar"
    STN = "São Tomé and Príncipe Dobra"
    SVC = "Salvadoran Colón"
    SZL = "Swazi Lilangeni"
    THB = "Thai Baht"
    TJS = "Tajikistani Somoni"
    TMT = "Turkmenistan Manat"
    TND = "Tunisian Dinar"
    TOP = "Tongan Paʻanga"
    TRY = "Turkish Lira"
    TTD = "Trinidad and Tobago Dollar"
    TWD = "New Taiwan Dollar"
    TZS = "Tanzanian Shilling"
    UAH = "Ukrainian Hryvnia"
    UGX = "Ugandan Shilling"
    USD = "United States Dollar"
    UYU = "Uruguayan Peso"
    UZS = "Uzbekistan Som"
    VES = "Venezuelan Bolívar"
    VND = "Vietnamese Dong"
    VUV = "Vanuatu Vatu"
    WST = "Samoan Tālā"
    XAF = "CFA Franc BEAC"
    XCD = "East Caribbean Dollar"
    XOF = "CFA Franc BCEAO"
    XPF = "CFP Franc"
    YER = "Yemeni Rial"
    ZAR = "South African Rand"
    ZMW = "Zambian Kwacha"
    ZWL = "Zimbabwean Dollar"

from enum import Enum

class ProductCategory(Enum):
    # Clothes
    T_SHIRTS = ("Clothes", "T-Shirts")
    DRESSES = ("Clothes", "Dresses")
    PANTS = ("Clothes", "Pants")
    JACKETS = ("Clothes", "Jackets")
    SWEATERS = ("Clothes", "Sweaters")
    SKIRTS = ("Clothes", "Skirts")
    SHORTS = ("Clothes", "Shorts")
    COATS = ("Clothes", "Coats")
    SUITS = ("Clothes", "Suits")
    UNDERWEAR = ("Clothes", "Underwear")
    SOCKS = ("Clothes", "Socks")
    
    # Shoes
    SNEAKERS = ("Shoes", "Sneakers")
    BOOTS = ("Shoes", "Boots")
    SANDALS = ("Shoes", "Sandals")
    FORMAL_SHOES = ("Shoes", "Formal Shoes")
    SLIPPERS = ("Shoes", "Slippers")
    HEELS = ("Shoes", "Heels")
    FLATS = ("Shoes", "Flats")
    TRAINERS = ("Shoes", "Trainers")
    
    # Accessories
    BELTS = ("Accessories", "Belts")
    HATS = ("Accessories", "Hats")
    BAGS = ("Accessories", "Bags")
    JEWELRY = ("Accessories", "Jewelry")
    SCARVES = ("Accessories", "Scarves")
    GLOVES = ("Accessories", "Gloves")
    SUNGLASSES = ("Accessories", "Sunglasses")
    WATCHES = ("Accessories", "Watches")
    WALLET = ("Accessories", "Wallets")
    
    # Electronics
    PHONES = ("Electronics", "Phones")
    LAPTOPS = ("Electronics", "Laptops")
    TABLETS = ("Electronics", "Tablets")
    HEADPHONES = ("Electronics", "Headphones")
    CAMERAS = ("Electronics", "Cameras")
    TVS = ("Electronics", "Televisions")
    SPEAKERS = ("Electronics", "Speakers")
    SMARTWATCHES = ("Electronics", "Smartwatches")
    GAMING_CONSOLES = ("Electronics", "Gaming Consoles")
    DRONES = ("Electronics", "Drones")
    
    # Home & Living
    FURNITURE = ("Home & Living", "Furniture")
    KITCHEN = ("Home & Living", "Kitchen")
    BEDDING = ("Home & Living", "Bedding")
    DECOR = ("Home & Living", "Decor")
    LIGHTING = ("Home & Living", "Lighting")
    RUGS = ("Home & Living", "Rugs")
    BATHROOM = ("Home & Living", "Bathroom")
    STORAGE = ("Home & Living", "Storage")
    CLEANING = ("Home & Living", "Cleaning")
    GARDEN = ("Home & Living", "Garden")
    
    # Travel & Tickets
    FLIGHT_TICKETS = ("Travel & Tickets", "Flight Tickets")
    TRAIN_TICKETS = ("Travel & Tickets", "Train Tickets")
    BUS_TICKETS = ("Travel & Tickets", "Bus Tickets")
    HOTEL_BOOKINGS = ("Travel & Tickets", "Hotel Bookings")
    TOUR_PACKAGES = ("Travel & Tickets", "Tour Packages")
    CRUISES = ("Travel & Tickets", "Cruises")
    CAR_RENTALS = ("Travel & Tickets", "Car Rentals")
    
    # Sports & Outdoors
    FITNESS = ("Sports & Outdoors", "Fitness")
    CAMPING = ("Sports & Outdoors", "Camping")
    BIKES = ("Sports & Outdoors", "Bikes")
    SPORTS_EQUIPMENT = ("Sports & Outdoors", "Sports Equipment")
    SWIMMING = ("Sports & Outdoors", "Swimming")
    HIKING = ("Sports & Outdoors", "Hiking")
    YOGA = ("Sports & Outdoors", "Yoga")
    TEAM_SPORTS = ("Sports & Outdoors", "Team Sports")
    OUTDOOR_GEAR = ("Sports & Outdoors", "Outdoor Gear")
    
    # Beauty & Health
    SKINCARE = ("Beauty & Health", "Skincare")
    MAKEUP = ("Beauty & Health", "Makeup")
    HAIRCARE = ("Beauty & Health", "Haircare")
    PERSONAL_CARE = ("Beauty & Health", "Personal Care")
    FRAGRANCES = ("Beauty & Health", "Fragrances")
    NAILS = ("Beauty & Health", "Nails")
    HEALTH_SUPPLEMENTS = ("Beauty & Health", "Health Supplements")
    ORAL_CARE = ("Beauty & Health", "Oral Care")
    
    # Toys & Kids
    ACTION_FIGURES = ("Toys & Kids", "Action Figures")
    DOLLS = ("Toys & Kids", "Dolls")
    BOARD_GAMES = ("Toys & Kids", "Board Games")
    PUZZLES = ("Toys & Kids", "Puzzles")
    EDUCATIONAL_TOYS = ("Toys & Kids", "Educational Toys")
    BABY_CLOTHING = ("Toys & Kids", "Baby Clothing")
    STROLLERS = ("Toys & Kids", "Strollers")
    CAR_SEATS = ("Toys & Kids", "Car Seats")
    
    # Food & Beverages
    SNACKS = ("Food & Beverages", "Snacks")
    BEVERAGES = ("Food & Beverages", "Beverages")
    FRESH_PRODUCE = ("Food & Beverages", "Fresh Produce")
    DAIRY = ("Food & Beverages", "Dairy")
    BAKERY = ("Food & Beverages", "Bakery")
    FROZEN_FOOD = ("Food & Beverages", "Frozen Food")
    CANNED_GOODS = ("Food & Beverages", "Canned Goods")
    
    # Office Supplies
    STATIONERY = ("Office Supplies", "Stationery")
    PRINTERS = ("Office Supplies", "Printers")
    INK_TONER = ("Office Supplies", "Ink & Toner")
    OFFICE_FURNITURE = ("Office Supplies", "Office Furniture")
    COMPUTERS = ("Office Supplies", "Computers")
    
    # Automotive & Tools
    CAR_PARTS = ("Automotive & Tools", "Car Parts")
    TOOLS = ("Automotive & Tools", "Tools")
    MOTORCYCLE_PARTS = ("Automotive & Tools", "Motorcycle Parts")
    ACCESSORIES_AUTO = ("Automotive & Tools", "Automotive Accessories")
    GARAGE_EQUIPMENT = ("Automotive & Tools", "Garage Equipment")
    